### ISSUE TITLE
Version 1.14.1 causes Polymer to not load in Firefox 43.0.3

### ISSUE THREAD

**Issue by JamesFigler** [Polymer/tools#1856]
We get the following errors when rendering our app in Firefox after upgrading to 1.14.1. Rolling back to 1.14.0 fixes the issue. This problem does not affect Chrome. 

```
TypeError: document.registerElement is not a function
 localhost:8080:775:1
TypeError: Polymer.Base._getExtendedPrototype is not a function
 localhost:8080:538:8
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: Polymer.Base._getExtendedPrototype is not a function
 localhost:8080:538:8
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: Polymer.Base._getExtendedPrototype is not a function
 localhost:8080:538:8
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: views.select is not a function
```
