### ISSUE TITLE
[6.0.0-prerelease.7] Cannot find module './runner/cli'

### ISSUE THREAD

**Issue by chrismbeckett** [Polymer/tools#3164]
I am able to test correctly with 6.0.0-prerelease.5, but after upgrading to 6.0.0-prerelease.7 I get the following error.

```
module.js:471
    throw err;
    ^

Error: Cannot find module './runner/cli'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Drive\Source\arsnebula\nebula-focus-behavior\node_modules\web-component-tester\runner.js:11:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
npm ERR! Test failed.  See above for more details.
```
I am running on Windows 10, Node 6.10.2, and WCT 6.0.0-prerelease.7.
