### ISSUE TITLE
cli version 1.7.2 doesn't work with polymer 2 and browser sync.

### ISSUE THREAD

**Issue by kaseyhinton** [Polymer/tools#422]
I recently upgraded my polymer-cli version to 1.7.2. This upgrade causes browser sync to not properly inject the script used for live reloading into the body of my application. It also caused weird map file issues where I was unable to break point in ts files. I am using Polymer 2, Typescript, Gulp, and Browser Sync. Reverting to polymer-cli@1.6.0 fixed my issues. I also tested a similar configuration in a polymer 1 project and had the same results.

Here is my gulp file
```
var gulp = require('gulp');
var exec = require('child_process').exec;
var browserSync = require('browser-sync').create();

gulp.task('compile', function (done) {
  exec('tsc -w', function (err, stdOut, stdErr) {
    console.log(stdOut);
    if (err) {
      done(err);
    } else {
      done();
    }
  });
});

gulp.task('polymerServe', function (done) {
  exec('polymer serve -p 8911 -v', function (err, stdOut, stdErr) {
    console.log(stdOut);
    if (err) {
      done(err);
    } else {
      done();
    }
  });
});

gulp.task('browser-sync', function () {
  browserSync.init({
    proxy: "localhost:8911"
  });
});

gulp.task('watch', ['browser-sync'], function () {

  var directoriesToWatch = ["src/**/*.js", "src/**/*.html", "*.js", "*.html", "images/*.*"]

  directoriesToWatch.forEach(function (directory) {
    console.log('Listening for changes at: ' + directory);
    var jsWatcher = gulp.watch(directory, {
      interval: 1000
    }).on('change', browserSync.reload);

    jsWatcher.on('change', function (event) {
      console.log('File ' + event.path + ' was ' + event.type);
    });
  });

});

gulp.task('default', ['compile', 'polymerServe', 'watch']);
```

**Comment by iSuslov** [comment]
After building polymer 2 project I have a huge error stack referencing that

`Uncaught TypeError: babelHelpers.assertThisInitialized is not a function`

**Comment by floribon** [comment]
I had a different issue with polymer-cli when upgrading from 1.6, "polymer build" crashes.
Is there any breaking change we should be aware of?
Using Polymer 2.6, TypeScript 2.7, Webpack 3.12

If this is unrelated and affecting visibility of this current issue I will move my message, thanks.

```
<--- Last few GCs --->

[42570:0x3ac36d0]   110048 ms: Mark-sweep 1419.3 (1559.6) -> 1419.1 (1560.6) MB, 1842.3 / 0.0 ms  allocation failure GC in old space requested
[42570:0x3ac36d0]   111835 ms: Mark-sweep 1419.1 (1560.6) -> 1419.1 (1525.6) MB, 1786.6 / 0.0 ms  last resort GC in old space requested
[42570:0x3ac36d0]   113665 ms: Mark-sweep 1419.1 (1525.6) -> 1419.1 (1520.1) MB, 1829.5 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x311068025879 <JSObject>
    1: set [native weak-collection.js:~27] [pc=0x35b7c828a229](this=0x212cd1d6b0d9 <JSWeakMap>,key=0x39fe441e72f1 <Node map = 0x37e8b4a29501>,value=0x32b066e2aff1 <Scope map = 0x37e8b4a24121>)
    2: new constructor(aka Scope) [/usr/local/google/home/floribon/.npm-global/lib/node_modules/polymer-cli/node_modules/@babel/traverse/lib/scope/index.js:~218] [pc=0x35b7c825654d](this=0x32b066e2aff1 <Sc...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [polymer]
 2: 0x8c20ec [polymer]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [polymer]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [polymer]
 5: v8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) [polymer]
 6: v8::internal::HashTable<v8::internal::ObjectHashTable, v8::internal::ObjectHashTableShape>::NewInternal(v8::internal::Isolate*, int, v8::internal::PretenureFlag) [polymer]
 7: v8::internal::HashTable<v8::internal::ObjectHashTable, v8::internal::ObjectHashTableShape>::New(v8::internal::Isolate*, int, v8::internal::PretenureFlag, v8::internal::MinimumCapacity) [polymer]
 8: v8::internal::HashTable<v8::internal::ObjectHashTable, v8::internal::ObjectHashTableShape>::EnsureCapacity(v8::internal::Handle<v8::internal::ObjectHashTable>, int, v8::internal::PretenureFlag) [polymer]
 9: v8::internal::ObjectHashTable::Put(v8::internal::Handle<v8::internal::ObjectHashTable>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int) [polymer]
10: v8::internal::JSWeakCollection::Set(v8::internal::Handle<v8::internal::JSWeakCollection>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int) [polymer]
11: v8::internal::Runtime_WeakCollectionSet(int, v8::internal::Object**, v8::internal::Isolate*) [polymer]
12: 0x35b7c7d042fd
Aborted
```

**Comment by lpellegr** [comment]
Same issue on my side. Updating the installation page to reference `polymer-cli@1.6.0` would be really convenient:

https://www.polymer-project.org/2.0/docs/tools/polymer-cli
